### ISSUE TITLE
Render in flutter

### ISSUE THREAD

**Issue by liangxianzhe** [timmaffett/mermaid.dart#1]
Hi @timmaffett . This package looks cool. 

Technically, we can use a Flutter TextField to take input markdown and render the graph in an embedded webview inside Flutter app below the TextField.

Just wondering if that's correct and have you tried that?

**Comment by timmaffett** [comment]
I have not used mermaid in a webview within flutter, but it should work just fine. 
   I would imagine that you could make a page similar to the example where you have a js routine that accepts a new mermaid source and renders it into the dom like the example does.    Then from flutter you would just call into the JS within the webview and the mermaid would be rendered and appear in the webview just like it does in the example.
   I would be interested in seeing what you come up with and would of course be happy to answer any questions or help resolve any issues that you run into.

**Comment by liangxianzhe** [comment]
Thanks. I will try it out in the coming months and then share it. Closing for now.

**Comment by MiniSuperDev** [comment]
@timmaffett @liangxianzhe Hello, I want to also render in flutter, but I don't know how to do it? Have either of you done this already?
